name: micro_dart
version: 0.0.1
description: A minimal command-line application.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: ">=0.13.0 <0.14.0"
  path: ">=1.3.3 <2.0.0"
  logging: ">=0.9.3 <0.10.0"
  logging_handlers: ">=0.8.0 <0.9.0"
dev_dependencies:
  unittest: any
